language: ruby
rvm:
  - 2.4.2

sudo: false

cache: bundler

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - USER="Travis CI"
    - EMAIL="travis@travis-ci.org"
    - GITHUB_REPO="github.com/${TRAVIS_REPO_SLUG}.git"

branches:
  only:
    - master
    - develop

before_install:
  - gem install gem-release --pre
  - ./scripts/bump-version.sh

script:
  - bundle exec jekyll build --config _test/_config.yml
  - bundle exec htmlproofer ./_site --disable-external

after_success:
  - ./scripts/merge-downstream.sh

deploy:
  - provider: rubygems
    on:
      branch: master
    api_key:
      secure: "RNKG1VHenOH/xa5Qax6nK8rEP4iS9rQ28jXOb0q3sgWbcgRoBm2B9lUl1WZ6gPcOIIlN+79FFXEzWJMM1NPxs9N5ZLHVQV35D8ApA2lFOU8C4jzgQstAIXh0Pa8HBHTnYbjHObobiuKmI4oqOQ/WV8I6281Ol+PcQizstLwiHI+soqRea94vuuOCqalaQL9zOXZHaqYyQYJSJOFWAyPO3+wjJU8lpN9Dt3n2J+XZujbdIG99otQAE+/dr+cy0ax4a8K0voEOQ9rVdSUjXMspsog7kT+qcVUehmcTfVRyWZcUPTgVgJ3vneWTtdRTVAK75TuENlPFJ0SsIYuHmIHigQpvdWBGFF43h+Ipm37Y+jRTdwxhhShmrfQ4Ljvnp/AahxHmMUSF12c0Ft0wPCsMqWbQJs9MZneTB5NXq+OvJDI2Ve8fYvrINgPdFv+tn8gE8tR8BU3nZB+gsFLzdOiJPfwCxf9xSTexWYCTSqFoo9LgML00g0BykQE9Nm4mY0/y4VqUjMCAoHnlh7hK7N2wFNBiGEcGtwmRVacCBWz42W5lX6T8KuM5nT10hOwXF+uVSUsSw7JglHOWYharegjnhnjS9fbbQCUXSuDuUunZWagTYKj4QM94BmMoEAT+RZ1LsKWR6SojjMB8Cms2J70TcqZBsO5CBGug1VWk6NzdNJI="
  - provider: releases
    api_key: ${GITHUB_TOKEN}
    file: "resume-theme-$(gem bump --pretend --no-commit | awk '{ print $3 }').gem"
    on:
      branch: master
