language: ruby
rvm:
  - 2.4.2

sudo: false

cache: bundler

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - USER="Travis CI"
    - EMAIL="travis@travis-ci.org"
    - REPO="sproogen/resume-theme"
    - GH_REPO="github.com/${REPO}.git"
    - secure: "IM3SuN/3YyGH6J1dzeXHQjkr6pr2o6kojg3drnjcR0MNEyvMx5Q5gBtYyJ/GvpWw0Ii/m7TnklaZ8gZaMZ+zky6vtu6tsJyIvKPJI0tFXTmen0UBbXQr/lVFJTt57M3TzZIgQDsmNU2bGwDhOsfShr/ZHTEjXxwxP9glPSwVTEFnkEHF7rzn7AVuSnWkSaueh/p+5XicKlZ5b7Aqx1Q5GWzSmSXKRV68ikYTbJElg8BDPP5XNDtrsfggBenr83jocIausL4g7uQK8vci0xiiTi8ODZ/HjdkofQpAP2waimydp8Jy6z3bINNHW94IVJ9/7Q5r36cmVz8KCKzrw/C8u+KMMvldJ5BoI/MRaBwhpBo+z3eqo149igWgYbYPwCJLqKAdJKps1Wj9MHopS6D1YJCOzpH/bvPN/g5Kj/zH4TwtUClkmlg/R1YDn7Vzvc+CNO8FW2+HZJ2ak2yogSd1b/yMzZeF9kMykkiAjFeUb8zuIJ808+Kcal+sp7Jyw833BJacQe8oBZkAzUKU2AmlMAGQnMtTbV59NXJ9/bT97EEHmAeJ49csi9UqYa06oiRRC+nsRun/x2PYovpEac5IksYELyHG3Ceoqi0gqKuuXQ+1wMxFUQbsvjbgC7x5S5XMOupeAE7wV7p+cZsI4U4p2ou9URI9NGRL76o9Ur990d0="

branches:
  only:
    - master
    - develop

before_install:
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      gem install gem-release --pre;
      git config --global user.email ${EMAIL};
      git config --global user.name ${USER};
      git checkout master;
      gem bump --skip-ci;
      gem tag --no-push;
      git push "https://${GH_TOKEN}@${GH_REPO}" master --tags;
    fi

script:
  - bundle exec jekyll build --config _test/_config.yml
  - bundle exec htmlproofer ./_site --disable-external

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      git fetch origin develop;
      git checkout develop;
      git merge master;
      git push "https://${GH_TOKEN}@${GH_REPO}" develop;
    fi

deploy:
  provider: rubygems
  on:
    branch: master
  api_key:
    secure: "RNKG1VHenOH/xa5Qax6nK8rEP4iS9rQ28jXOb0q3sgWbcgRoBm2B9lUl1WZ6gPcOIIlN+79FFXEzWJMM1NPxs9N5ZLHVQV35D8ApA2lFOU8C4jzgQstAIXh0Pa8HBHTnYbjHObobiuKmI4oqOQ/WV8I6281Ol+PcQizstLwiHI+soqRea94vuuOCqalaQL9zOXZHaqYyQYJSJOFWAyPO3+wjJU8lpN9Dt3n2J+XZujbdIG99otQAE+/dr+cy0ax4a8K0voEOQ9rVdSUjXMspsog7kT+qcVUehmcTfVRyWZcUPTgVgJ3vneWTtdRTVAK75TuENlPFJ0SsIYuHmIHigQpvdWBGFF43h+Ipm37Y+jRTdwxhhShmrfQ4Ljvnp/AahxHmMUSF12c0Ft0wPCsMqWbQJs9MZneTB5NXq+OvJDI2Ve8fYvrINgPdFv+tn8gE8tR8BU3nZB+gsFLzdOiJPfwCxf9xSTexWYCTSqFoo9LgML00g0BykQE9Nm4mY0/y4VqUjMCAoHnlh7hK7N2wFNBiGEcGtwmRVacCBWz42W5lX6T8KuM5nT10hOwXF+uVSUsSw7JglHOWYharegjnhnjS9fbbQCUXSuDuUunZWagTYKj4QM94BmMoEAT+RZ1LsKWR6SojjMB8Cms2J70TcqZBsO5CBGug1VWk6NzdNJI="
