language: ruby
rvm:
  - 2.4.2 # The version of ruby on GitHub Pages

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build

cache: bundler # caching bundler gem packages will speed up build

branches:
  only:
    - master
    - develop

script:
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site --disable-external