# Personal info
name: Brett Harris
title: Senior Network System Administrator
email: brett.h@email.co.uk
website: www.github.com/sproogen/resume-theme

# Social links
twitter_username: jekyllrb
github_username:  jekyll
dribbble_username: jekyll
facebook_username: jekyll
flickr_username: jekyll
instagram_username: jekyll
linkedin_username: jekyll
pinterest_username: jekyll
youtube_username: jekyll
googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: > # this means to ignore newlines until the next config item.
  Write an awesome description about yourself here, this supports markdown, so you can add [links](http://foobar.com) and highlight things <mark>like this</mark>.
  <br>
  <br>
  You can even add break lines and anything else markdown supports.

# Build settings
# theme: minima

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag