name: Bump Version

on:
  workflow_run:
    workflows: [ "Build and Test" ]
    types:
      - completed

jobs:
  bump-version:
    name: Bump Version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Install gem-release
      run: gem install gem-release
    - run: |
        CURRENT_VERSION=v$(gem bump --pretend --no-commit | awk '{ print $3 }');
        echo "$CURRENT_VERSION"
