name: Bump Version

on:
  workflow_run:
    workflows: [ "Build and Test" ]
    pull_request: [ master ]
    types:
      - completed

jobs:
  build-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Install gem-release
      run: |
        CURRENT_VERSION=v$(gem bump --pretend --no-commit | awk '{ print $3 }');
        echo "$CURRENT_VERSION"